/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DistanceStatusCard: typeof import('./src/components/info-panel/DistanceStatusCard.vue')['default']
    DroneStatusCard: typeof import('./src/components/info-panel/DroneStatusCard.vue')['default']
    DroneStatusCard1: typeof import('./src/components/panels/DroneStatusCard1.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    InstructionsCard: typeof import('./src/components/panels/InstructionsCard.vue')['default']
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    MapTypeDownloadSection: typeof import('./src/components/MapTypeDownloadSection.vue')['default']
    MissionProgressCard: typeof import('./src/components/info-panel/MissionProgressCard.vue')['default']
    OperatorInstructionsCard: typeof import('./src/components/info-panel/OperatorInstructionsCard.vue')['default']
    ProgressCard: typeof import('./src/components/panels/ProgressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    StatusCard: typeof import('./src/components/panels/StatusCard.vue')['default']
    SurveyButtonCard: typeof import('./src/components/info-panel/SurveyButtonCard.vue')['default']
    VehicleStatusCard: typeof import('./src/components/info-panel/VehicleStatusCard.vue')['default']
    VehicleStatusCard1: typeof import('./src/components/panels/VehicleStatusCard1.vue')['default']
  }
}
